<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Inscription</title>
	</head>
	<body>

		<h2>Création d'un nouveau groupe</h2>


		<form name = "formulaireNouveauGroupe" method="post" action = "">
			<p> <input type="text" name="nomGroupe" placeholder="Nom du Groupe" size="25" value = "<?= $_POST['nomGroupe'] ?>"/> </p>
		  <p> <input type="number" name="placesLibres" placeholder="Nombre de places" size="25" value = "<?= $_POST['placesLibres'] ?>" /> </p>
      <p>
        <select name="sport">
          <option value="0"> -- Sélectionnez un sport -- </option>
          <option value="Aïkido"> Aïkido </option>
          <option value="Alpinisme"> Alpinisme </option>
          <option value="Athlétisme"> Athlétisme </option>
          <option value="Aviron"> Aviron </option>
          <option value="Aérobic"> Aérobic </option>
          <option value="Apnée"> Apnée </option>
          <option value="Badminton"> Badminton </option>
          <option value="Balle au tambourin"> Balle au tambourin </option>
          <option value="Bando"> Bando </option>
          <option value="Baseball"> Baseball </option>
          <option value="Base jump"> Base jump </option>
          <option value="Basket-ball"> Basket-ball </option>
          <option value="Bateau-Dragon"> Bateau-Dragon </option>
          <option value="Biathlon"> Biathlon </option>
          <option value="BMX"> BMX </option>
          <option value="Billard"> Billard </option>
          <option value="Bobsleigh"> Bobsleigh </option>
          <option value="Bowling"> Bowling </option>
          <option value="Boxe"> Boxe </option>
          <option value="Canoë-kayak"> Canoë-kayak </option>
          <option value="Canyoning"> Canyoning </option>
          <option value="Course"> Course </option>
          <option value="Course d'orientation"> Course d'orientation </option>
          <option value="Cricket"> Cricket </option>
          <option value="Croquet"> Croquet </option>
          <option value="Crosse"> Crosse </option>
          <option value="Curling"> Curling </option>
          <option value="Cyclisme"> Cyclisme </option>
          <option value="Capoeira"> Capoeira </option>
          <option value="Cheerleading"> Cheerleading </option>
          <option value="Conduite sur glace"> Conduite sur glace </option>
          <option value="Catch"> Catch </option>
          <option value="canoë"> canoë </option>
          <option value="Danse"> Danse </option>
          <option value="Deltaplane"> Deltaplane </option>
          <option value="Décathlon"> Décathlon </option>
          <option value="Équitation"> Équitation </option>
          <option value="Escalade"> Escalade </option>
          <option value="Escrime"> Escrime </option>
          <option value="Échecs"> Échecs </option>
          <option value="Esport"> Esport </option>
          <option value="Floorball"> Floorball </option>
          <option value="Football"> Football </option>
          <option value="Football américain"> Football américain </option>
          <option value="Futsal"> Futsal </option>
          <option value="Golf"> Golf </option>
          <option value="Gymnastique"> Gymnastique </option>
          <option value="Hakko-Ryu"> Hakko-Ryu </option>
          <option value="Haltérophilie"> Haltérophilie </option>
          <option value="Handball"> Handball </option>
          <option value="Hockey sur gazon"> Hockey sur gazon </option>
          <option value="Hockey sur glace"> Hockey sur glace </option>
          <option value="Horse-ball"> Horse-ball </option>
          <option value="Hurling"> Hurling </option>
          <option value="Iaïdo"> Iaïdo </option>
          <option value="Iaïjutsu"> Iaïjutsu </option>
          <option value="Jeu de paume"> Jeu de paume </option>
          <option value="Ju-Jitsu"> Ju-Jitsu </option>
          <option value="Joutes nautiques"> Joutes nautiques </option>
          <option value="Judo"> Judo </option>
          <option value="Javelot tir sur cible"> Javelot tir sur cible </option>
          <option value="Jumping"> Jumping </option>
          <option value="Java"> java </option>
          <option value="Jerk"> jerk </option>
          <option value="Jogging"> jogging </option>
          <option value="Karaté"> Karaté </option>
          <option value="Kathak"> kathak</option>
          <option value="Kick-boxing"> Kick-boxing </option>
          <option value="Kitesurfing"> Kitesurfing </option>
          <option value="Kronum"> Kronum </option>
          <option value="Karting"> Karting </option>
          <option value="Keirin"> Keirin </option>
          <option value="Kendo"> Kendo </option>
          <option value="Kempo"> Kempo </option>
          <option value="Kin-ball"> Kin-ball </option>
          <option value="Kung fu"> Kung fu </option>
          <option value="Krav maga"> Krav maga </option>
          <option value="Lancer du javelot"> Lancer du javelot </option>
          <option value="Luge de course"> Luge de course</option>
          <option value="Lutte"> Lutte </option>
          <option value="Muay thaï"> Muay thaï (boxe thaïladaise) </option>
          <option value="Motocross"> Motocross </option>
          <option value="Musculation"> Musculation </option>
          <option value="Marathon"> Marathon </option>
          <option value="Marche"> marche </option>
          <option value="Naban"> Naban (lutte birmane) </option>
          <option value="Natation"> Natation </option>
          <option value="Natation synchronisée"> Natation synchronisée </option>
          <option value="Nautisme"> Nautisme</option>
          <option value="Optimist"> Optimist </option>
          <option value="Parachutisme"> Parachutisme </option>
          <option value="Parapente"> Parapente </option>
          <option value="Patinage artistique"> Patinage artistique </option>
          <option value="Patinage de vitesse"> Patinage de vitesse </option>
          <option value="Pêche"> Pêche </option>
          <option value="Pelote basque"> Pelote basque </option>
          <option value="Pentathlon "> Pentathlon  </option>
          <option value="Pétanque"> Pétanque </option>
          <option value="Ping-Pong"> Ping-Pong </option>
          <option value="Plongée"> Plongée </option>
          <option value="Paintball"> Paintball </option>
          <option value="Paddle"> Paddle </option>
          <option value="Parkour"> Parkour </option>
          <option value="Qi gong"> Qi gong </option>
          <option value="Quadrille"> Quadrille </option>
          <option value="Polo"> polo </option>
          <option value="Rafting"> Rafting </option>
          <option value="Rallye automobile"> Rallye automobile </option>
          <option value="Régate"> Régate </option>
          <option value="Ringuette"> Ringuette </option>
          <option value="Rink hockey"> Rink hockey </option>
          <option value="Roller"> Roller </option>
          <option value="Rugby"> Rugby </option>
          <option value="Savate"> Savate </option>
          <option value="Shinty"> Shinty </option>
          <option value="Skateboard"> Skateboard </option>
          <option value="Skater hockey"> Skater hockey </option>
          <option value="Skeleton"> Skeleton </option>
          <option value="Ski alpin"> Ski alpin </option>
          <option value="Ski de fond"> Ski de fond </option>
          <option value="Ski nordique"> Ski nordique </option>
          <option value="Ski nautique"> Ski nautique </option>
          <option value="Slamball"> Slamball </option>
          <option value="Snowboard"> Snowboard </option>
          <option value="Softball"> Softball </option>
          <option value="Spéléologie"> Spéléologie </option>
          <option value="Squash"> Squash </option>
          <option value="Sumo"> Sumo </option>
          <option value="Surf"> Surf </option>
          <option value="Supermotard"> Supermotard </option>
          <option value="Salsa"> Salsa </option>
          <option value="Taekwondo"> Taekwondo </option>
          <option value="Tambourin"> Tambourin </option>
          <option value="Tae Bo"> Tae Bo </option>
          <option value="Tai Chi"> Tai Chi </option>
          <option value="Taihojutsu"> Taihojutsu </option>
          <option value="Tchoukball"> Tchoukball </option>
          <option value="Tennis"> Tennis </option>
          <option value="Tennis léger"> Tennis léger </option>
          <option value="Twirling"> Twirling </option>
          <option value="Tennis de table"> Tennis de table </option>
          <option value="Tir"> Tir </option>
          <option value="Tir à l'arc"> Tir à l'arc </option>
          <option value="Triathlon"> Triathlon </option>
          <option value="Tango"> Tango </option>
          <option value="Tricking"> Tricking </option>
          <option value="ULM"> ULM </option>
          <option value="Ultimate"> Ultimate </option>
          <option value="Unihockey"> Unihockey </option>
          <option value="Varappe"> Varappe </option>
          <option value="Voile"> Voile </option>
          <option value="Volata"> Volata </option>
          <option value="Volley-ball"> Volley-ball </option>
          <option value="VTT"> VTT </option>
          <option value="Voltige"> Voltige </option>
          <option value="Valse"> Valse </option>
          <option value="Wakeboard"> Wakeboard </option>
          <option value="Water polo"> Water polo </option>
          <option value="Wing Chun"> Wing Chun </option>
          <option value="Yoga"> Yoga </option>
          <option value="Zen Hakko Kaï"> Zen Hakko Kaï </option>
          <option value="Zumba"> Zumba </option>
          <option value="Zouk"> Zouk </option>
        </select>
      </p>

      <p>
				<select name="departement" >
					<option value="0"> -- Sélectionner votre Département -- </option>
					<option value="Ain" <?php if ($_POST['departement']=="Ain"){?> selected <?php }?> >01 - Ain</option>
					<option value="Aisne">02 - Aisne</option>
					<option value="Allier">03 - Allier</option>
					<option value="Alpes-de-Haute-Provence">04 - Alpes-de-Haute-Provence</option>
					<option value="Hautes-Alpes">05 - Hautes-Alpes</option>
					<option value="Alpes-Maritimes">06 - Alpes-Maritimes</option>
					<option value="Ardeche">07 - Ardeche</option>
					<option value="Ardennes">08 - Ardennes</option>
					<option value="Ariege">09 - Ariege</option>
					<option value="Aube">10 - Aube</option>
					<option value="Aude">11 - Aude</option>
					<option value="Aveyron">12 - Aveyron</option>
					<option value="Bouches-du-Rhone">13 - Bouches-du-Rhone</option>
					<option value="Calvados">14 - Calvados</option>
					<option value="Cantal">15 - Cantal</option>
					<option value="Charente">16 - Charente</option>
					<option value="Charente-Maritime">17 - Charente-Maritime</option>
					<option value="Cher">18 - Cher</option>
					<option value="Correze">19 - Correze</option>
					<option value="Corse-du-Sud">2A - Corse-du-Sud</option>
					<option value="Haute-Corse">2B - Haute-Corse</option>
					<option value="Cote-d'Or">21 - Cote-d'Or</option>
					<option value="Cotes-d'Armor">22 - Cotes-d'Armor</option>
					<option value="Creuse">23 - Creuse</option>
					<option value="Dordogne">24 - Dordogne</option>
					<option value="Doubs">25 - Doubs</option>
					<option value="Drome">26 - Drome</option>
					<option value="Eure">27 - Eure</option>
					<option value="Eure-et-Loir">28 - Eure-et-Loir</option>
					<option value="Finistere">29 - Finistere</option>
					<option value="Gard">30 - Gard</option>
					<option value="Haute-Garonne">31 - Haute-Garonne</option>
					<option value="Gers">32 - Gers</option>
					<option value="Gironde">33 - Gironde</option>
					<option value="Herault">34 - Herault</option>
					<option value="Ille-et-Vilaine">35 - Ille-et-Vilaine</option>
					<option value="Indre">36 - Indre</option>
					<option value="Indre-et-Loire">37 - Indre-et-Loire</option>
					<option value="Isere">38 - Isere</option>
					<option value="Jura">39 - Jura</option>
					<option value="Landes">40 - Landes</option>
					<option value="Loir-et-Cher">41 - Loir-et-Cher</option>
					<option value="Loire">42 - Loire</option>
					<option value="Haute-Loire">43 - Haute-Loire</option>
					<option value="Loire-Atlantique">44 - Loire-Atlantique</option>
					<option value="Loiret">45 - Loiret</option>
					<option value="Lot">46 - Lot</option>
					<option value="Lot-et-Garonne">47 - Lot-et-Garonne</option>
					<option value="Lozere">48 - Lozere</option>
					<option value="Maine-et-Loire">49 - Maine-et-Loire</option>
					<option value="Manche">50 - Manche</option>
					<option value="Marne">51 - Marne</option>
					<option value="Haute-Marne">52 - Haute-Marne</option>
					<option value="Mayenne">53 - Mayenne</option>
					<option value="Meurthe-et-Moselle">54 - Meurthe-et-Moselle</option>
					<option value="Meuse">55 - Meuse</option>
					<option value="Morbihan">56 - Morbihan</option>
					<option value="Moselle">57 - Moselle</option>
					<option value="Nievre">58 - Nievre</option>
					<option value="Nord">59 - Nord</option>
					<option value="Oise">60 - Oise</option>
					<option value="Orne">61 - Orne</option>
					<option value="Pas-de-Calais">62 - Pas-de-Calais</option>
					<option value="Puy-de-Dome">63 - Puy-de-Dome</option>
					<option value="Pyrenees-Atlantiques">64 - Pyrenees-Atlantiques</option>
					<option value="Hautes-Pyrenees">65 - Hautes-Pyrenees</option>
					<option value="Pyrenees-Orientales">66 - Pyrenees-Orientales</option>
					<option value="Bas-Rhin">67 - Bas-Rhin</option>
					<option value="Haut-Rhin">68 - Haut-Rhin</option>
					<option value="Rhone">69 - Rhone</option>
					<option value="Haute-Saone">70 - Haute-Saone</option>
					<option value="Saone-et-Loire">71 - Saone-et-Loire</option>
					<option value="Sarthe">72 - Sarthe</option>
					<option value="Savoie">73 - Savoie</option>
					<option value="Haute-Savoie">74 - Haute-Savoie</option>
					<option value="Paris">75 - Paris</option>
					<option value="Seine-Maritime">76 - Seine-Maritime</option>
					<option value="Seine-et-Marne">77 - Seine-et-Marne</option>
					<option value="Yvelines">78 - Yvelines</option>
					<option value="Deux-Sevres">79 - Deux-Sevres</option>
					<option value="Somme">80 - Somme</option>
					<option value="Tarn">81 - Tarn</option>
					<option value="Tarn-et-Garonne">82 - Tarn-et-Garonne</option>
					<option value="Var">83 - Var</option>
					<option value="Vaucluse">84 - Vaucluse</option>
					<option value="Vendee<">85 - Vendee</option>
					<option value="Vienne">86 - Vienne</option>
					<option value="Haute-Vienne">87 - Haute-Vienne</option>
					<option value="Vosges">88 - Vosges</option>
					<option value="Yonne">89 - Yonne</option>
					<option value="Territoire de Belfort">90 - Territoire de Belfort</option>
					<option value="Essonne">91 - Essonne</option>
					<option value="Hauts-de-Seine">92 - Hauts-de-Seine</option>
					<option value="Seine-Saint-Denis">93 - Seine-Saint-Denis</option>
					<option value="Val-de-Marne">94 - Val-de-Marne</option>
					<option value="Val-d'Oise">95 - Val-d'Oise</option>
					<option value="Guadeloupe">971 - Guadeloupe</option>
					<option value="Martinique">972 - Martinique</option>
					<option value="Guyane">973 - Guyane</option>
					<option value="Réunion">974 - Réunion</option>
					<option value="Saint-Pierre-et-Miquelon">975 - Saint-Pierre-et-Miquelon</option>
					<option value="Terres-australes-et-antarctiques-françaises">984 - Terres-australes-et-antarctiques-françaises</option>
					<option value="Mayotte">985 - Mayotte</option>
					<option value="Wallis-et-Futuna">986 - Wallis-et-Futuna</option>
					<option value="Polynesie-française">987 - Polynesie-française</option>
					<option value="Nouvelle-Caledonie">988 - Nouvelle-Caledonie</option>
				</select>
			</p>

			<p> <input name="creer" type="submit" value="Créer"> </p>
		</form>
	</body>
</html>
